### ISSUE TITLE
unTimeout on-start relies on cache; often fails

### ISSUE THREAD

**Issue by lachlan2k** [jtkiesel/bigbro#8]
When the bot starts & attempts to unTimeout DQs that have expired during downtime, it relies on Discord.js's cache:
https://github.com/jtkiesel/bigbro/blob/14d5afc7151d644ee3ba6113ba311d9c061efa29/src/index.ts#L98-L110
https://github.com/jtkiesel/bigbro/blob/14d5afc7151d644ee3ba6113ba311d9c061efa29/src/commands/dq.ts#L47-L62

However, this is unlikely to have been cached on-start, and as such, this often fails.

We should probably look into the following:

- Use something along the lines of `const guild = await client.guilds.fetch(guildID); const member = guild.member(memberID)`.
- Only remove the DB record if the member is unTime'd out successfully

**Comment by jtkiesel** [comment]
The switch to using Discord's timeout API rather than our own has caused this issue to be OBE.
