### ISSUE TITLE
Invite logging unreliable

### ISSUE THREAD

**Issue by lachlan2k** [jtkiesel/bigbro#9]
When a user joins, we attempt to figure out which invited they used to join by searching for an invite that had its usage increase.
https://github.com/jtkiesel/bigbro/blob/14d5afc7151d644ee3ba6113ba311d9c061efa29/src/index.ts#L201

However, this leads to a slight race condition, as sometimes this hasn't been updated by the time we check. So, when Alice joins on invite ABC, it shows "Alice joined on invite: ", then when Bob joins on invite XYZ, it shows "Bob joined on invite: ABC".

Suggestions:
 * If we can't find an invite that increased in usage, poll 3 times. If no invite is still found, add a more descriptive message "No invite was found, the next detected invite may be incorrect"
   * This might lead to another race condition if 2 users join simultaneously...? But this whole solution inherently race-y ¯\\\_(ツ)_/¯

**Comment by jtkiesel** [comment]
This feature was removed from the bot, and now that Discord has "join method" as a column of the "Members" table, this feature is no longer needed.
